version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: slax_postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slax_dev
    ports:
      - "5432:5432"
    volumes:
      - slax_data:/var/lib/postgresql/data

volumes:
  slax_data:
